### ISSUE TITLE
Create Demo to Inject Arbitrary Telemetry Data over BLE into GPMF

### ISSUE THREAD

**Issue by betzuka** [gopro/OpenGoPro#220] opened 2022-08-16 16:00 UTC
Please provide an example of how we can inject arbitrary telemetry data from an external paired device over BLE so that is is included in the interleaved GPMF track of the camera recording. I am not talking about internal camera telemetry which is already included in the GPMF track, but additional telemetry from an external device. I believe this is possible and has been done previously but there is zero documentation.

**Comment by fr33z3** [comment] 2023-10-31 16:37
Any updates regarding this topic?

**Comment by tcamise-gpsw** [comment] 2023-12-07 17:43
Duplicate of #392

**Closed by tcamise-gpsw** 2023-12-07 17:43 UTC
Labels: enhancement, help wanted, demos

**Comment by fr33z3** [comment] 2024-01-17 13:29
Bump?
