### ISSUE TITLE
Stream high 4K video streams over USB

### ISSUE THREAD

**Issue by Ektacom** [gopro/OpenGoPro#503] opened 2024-03-29 13:07 UTC
I would like to stream high quality video over USB.

I'm always frustrated to have a camera able to make high quality video and not to have any solution to stream in real time these high quality videos (e.g. 4K videos). We can only download a posteriori the recorded videos.
I think this could be easily done: instead of writing the compressed video on the SD card, the video should be packetised and stream over the USB (USB have a high bandwidth). Maybe, it could even be possible to stream and record at the same time.

A lot of IP cameras propose this solution but they are not dedicated to sport applications. Having this functionnality on a gopro could be a nice addon.

**Comment by tcamise-gpsw** [comment] 2024-04-10 22:26
duplicate of https://github.com/gopro/OpenGoPro/issues/173

**Closed by tcamise-gpsw** 2024-04-10 22:26 UTC
Labels: enhancement, triage
