### ISSUE TITLE
GoPro Max Support

### ISSUE THREAD

**Issue by SebTheRed** [gopro/OpenGoPro#436] opened 2023-11-29 03:56 UTC
Hello a project I am working on needs to simply trigger the capture of a 360 picture from an HTTP request, nothing more. I would be willing to write docs or something in exchange for feature.

Thank you!

**Comment by tcamise-gpsw** [comment] 2023-12-06 20:00
duplicate of #160

**Closed by tcamise-gpsw** 2023-12-06 20:00 UTC
Labels: enhancement
