### ISSUE TITLE
Stream audio/video as well as metadata

### ISSUE THREAD

**Issue by Ektacom** [gopro/OpenGoPro#502] opened 2024-03-29 09:56 UTC
It is already possible to stream audio and video via webcam mode but unfortunately metadata are not streamed. For UAV application (and more generally robotics application) having the metadata streams with video would be very usefull to make it possible to run some usefull algorithms like VIO algoritm (Visual Inertial Odometry algorithm). 

That's why I would like to have during audio and video streaming the possibility to stream also the metadata (in particular IMU data).

**Comment by tcamise-gpsw** [comment] 2024-04-11 18:28
Duplicate of #203

**Closed by tcamise-gpsw** 2024-04-11 18:28 UTC
Labels: enhancement, triage
